<a href="https://colab.research.google.com/github/syibrahima31/Scientific-Programming-/blob/main/correction_TP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importation des packages 
import numpy as np 

### Probléme 1 : 

<br/> 

1 . Création de. x 

In [5]:
x = np.array([1,2,3,4,5])

2 . affichage du type de x et sa taille   

In [8]:
print(f"le type de x est :{type(x)}")
print(f"la taille de x : {x.shape}")

le type de x est :<class 'numpy.ndarray'>
la taille de x : (5,)


3 . Extraction du premier element et du dernier element 

In [10]:
# premier element 
x[0]

#denier elements 
x[x.shape[0]-1]

x[-1]

5

4 . Extraction des trois premiers elements et les ctocker dans un vecteur nommé `a`


In [13]:
a = x[:3]
print(a)

[1 2 3]


5 . Extraction des deux premiers élts et le 5éme elts puis stocker dans `b`

In [17]:
# indexation multiple 
x[[0,1,4]]

# boolean indexing 
b = x[[True, True, False, False, True]]

6 .Additionner le nombre 10 au vecteur `x` 

In [19]:
# le broadasting 
(x + 10)*2  


array([22, 24, 26, 28, 30])

7. Additionner a + b , puis commenter le resultat 
> les opérateurs en numpy sont vectorisés 

In [21]:
a + b 

array([2, 4, 8])

8 .  Effectuer l'addition a + x 
> Erreur va se déclancher car l'opération de broadcasting n'est pa défini 

In [33]:
a + x 

9. multiplier le vecteur par le scalaire `c` fixé à 2 

In [34]:
x * 2 

array([ 2,  4,  6,  8, 10])

10. Multiplication de a et b 

In [47]:
a * b 

array([ 1,  4, 15])

11. Multiplication x et a 
> Erreur car le broadcasting n'est pas défini 

In [51]:
print(x.shape)
print(a.shape)

(5,)
(3,)


12. Recuper les postion des multiple de 2 puis stocker dans `ind`

In [35]:
x % 2 == 0 

array([False,  True, False,  True, False])

In [46]:
# premiere technique 
ind  = np.where(x% 2==0)[0]
x[ind]

# second technique avec le booléan indexing 

ind = (x%2==0) 
x[ind]

array([2, 4])

13. Afficher les elements de x qui sont multiple 3 et de 2 

In [58]:
test  = (x % 3 ==0) &  (x % 2 ==0)
x[test]

array([], dtype=int64)

14. Afficher les elements de x qui sont multiple 3 ou  de 2 

In [59]:
test  = (x % 3 ==0) |  (x % 2 ==0)
x[test]

array([2, 3, 4])

15. la somme de x 

In [61]:
x.sum()

15

In [62]:
np.sum(x)

15

16. Remplacer le premier element par 4 

In [65]:
x[0] = 4 
x 

array([4, 2, 3, 4, 5])

17. Remplacer le dernier element par une valeur manquante 

In [74]:
 x = x.astype(float)
 x.dtype
 x[-1] = np.nan

In [82]:
np.nansum(x)

13.0

In [83]:
del x 